//go:build windows

package main

import (
	"os/exec"
	"syscall"
	"time"
)

var (
	kernel32           = syscall.NewLazyDLL("kernel32.dll")
	procSetErrorMode   = kernel32.NewProc("SetErrorMode")
	procSetConsoleCtrl = kernel32.NewProc("SetConsoleCtrlHandler")
)

func init() {
	// Suppress Windows Error Reporting crash dialogs for this process and its
	// children. Without this, a crashing test binary pops a WER dialog that
	// blocks the parent process (especially in PowerShell).
	const (
		semFailCriticalErrors = 0x0001
		semNoGPFaultErrorBox  = 0x0002
	)
	procSetErrorMode.Call(uintptr(semFailCriticalErrors | semNoGPFaultErrorBox))

	// Install a ctrl handler that ignores CTRL_C and CTRL_BREAK events.
	// Child process crashes can generate spurious console ctrl events that
	// kill the parent pipeline (promise.exe → verify.exe → PowerShell).
	// Unlike SetConsoleCtrlHandler(NULL, TRUE), a callback handler is NOT
	// inherited by child processes, so spawned processes (os.execute, etc.)
	// retain normal ctrl handling.
	procSetConsoleCtrl.Call(syscall.NewCallback(ctrlHandler), 1)
}

// ctrlHandler is a Windows console ctrl handler callback. It ignores
// CTRL_C_EVENT and CTRL_BREAK_EVENT (returns TRUE to suppress them)
// but lets other events (CTRL_CLOSE, CTRL_LOGOFF, CTRL_SHUTDOWN) through.
func ctrlHandler(ctrlType uint) uintptr {
	const (
		ctrlCEvent     = 0
		ctrlBreakEvent = 1
	)
	if ctrlType == ctrlCEvent || ctrlType == ctrlBreakEvent {
		return 1 // TRUE = handled, don't terminate
	}
	return 0 // FALSE = pass to next handler
}

// sanitizeExitCode maps Windows crash exit codes (negative values like
// 0xC0000005 / STATUS_ACCESS_VIOLATION) to 1. Raw crash codes cause
// PowerShell to enter debug mode, breaking the entire pipeline.
func sanitizeExitCode(code int) int {
	if code < 0 || code > 125 {
		return 1
	}
	return code
}

// isolateProcessGroup sets CREATE_NEW_PROCESS_GROUP on a command so that
// child crashes don't send CTRL_C_EVENT to the parent's console group.
// Without this, a crashing opt.exe or test binary kills the entire process
// tree (verify.exe → promise.exe) in PowerShell/cmd.exe.
func isolateProcessGroup(cmd *exec.Cmd) {
	cmd.SysProcAttr = &syscall.SysProcAttr{
		CreationFlags: syscall.CREATE_NEW_PROCESS_GROUP,
	}
}

// detachFromConsole sets CREATE_NEW_PROCESS_GROUP | CREATE_NO_WINDOW on a
// command, fully detaching it from the parent's console. Use this for
// background tool processes (opt, llc, lld) that don't need console I/O.
// This prevents them from receiving CTRL_C events generated by other
// processes on the same console.
func detachFromConsole(cmd *exec.Cmd) {
	const createNoWindow = 0x08000000
	cmd.SysProcAttr = &syscall.SysProcAttr{
		CreationFlags: syscall.CREATE_NEW_PROCESS_GROUP | createNoWindow,
	}
}

// setupProcessGroupKill configures a command to kill its process on context
// cancellation. On Windows, Process.Kill terminates the process; child process
// cleanup relies on the OS job object behavior.
func setupProcessGroupKill(cmd *exec.Cmd) {
	isolateProcessGroup(cmd)
	cmd.Cancel = func() error {
		return cmd.Process.Kill()
	}
	cmd.WaitDelay = 3 * time.Second
}
