// Generated by the Promise compiler — DO NOT EDIT
// Regenerated on each `promise build` with all built-in type layouts.
// During compilation, this header is force-included via -include flag.
#ifndef PROMISE_BINDINGS_H
#define PROMISE_BINDINGS_H

#include <stdint.h>

// === Built-in Type Layouts ===

// bool
typedef struct { } promise_bool_t;
typedef struct { promise_bool_t* _type; } promise_bool_m;
typedef struct { promise_bool_m* _variant; } promise_bool_i;
typedef struct {
    void*                _vtable;
    promise_bool_i*      _instance;
    uint8_t              raw;
} promise_bool_v;

// char
typedef struct { } promise_char_t;
typedef struct { promise_char_t* _type; } promise_char_m;
typedef struct { promise_char_m* _variant; } promise_char_i;
typedef struct {
    void*                _vtable;
    promise_char_i*      _instance;
    int32_t              raw;
} promise_char_v;

// f32
typedef struct { } promise_f32_t;
typedef struct { promise_f32_t* _type; } promise_f32_m;
typedef struct { promise_f32_m* _variant; } promise_f32_i;
typedef struct {
    void*                _vtable;
    promise_f32_i*       _instance;
    float                raw;
} promise_f32_v;

// f64
typedef struct { } promise_f64_t;
typedef struct { promise_f64_t* _type; } promise_f64_m;
typedef struct { promise_f64_m* _variant; } promise_f64_i;
typedef struct {
    void*                _vtable;
    promise_f64_i*       _instance;
    double               raw;
} promise_f64_v;

// i8
typedef struct { } promise_i8_t;
typedef struct { promise_i8_t* _type; } promise_i8_m;
typedef struct { promise_i8_m* _variant; } promise_i8_i;
typedef struct {
    void*                _vtable;
    promise_i8_i*        _instance;
    int8_t               raw;
} promise_i8_v;

// i16
typedef struct { } promise_i16_t;
typedef struct { promise_i16_t* _type; } promise_i16_m;
typedef struct { promise_i16_m* _variant; } promise_i16_i;
typedef struct {
    void*                _vtable;
    promise_i16_i*       _instance;
    int16_t              raw;
} promise_i16_v;

// i32
typedef struct { } promise_i32_t;
typedef struct { promise_i32_t* _type; } promise_i32_m;
typedef struct { promise_i32_m* _variant; } promise_i32_i;
typedef struct {
    void*                _vtable;
    promise_i32_i*       _instance;
    int32_t              raw;
} promise_i32_v;

// i64
typedef struct { } promise_i64_t;
typedef struct { promise_i64_t* _type; } promise_i64_m;
typedef struct { promise_i64_m* _variant; } promise_i64_i;
typedef struct {
    void*                _vtable;
    promise_i64_i*       _instance;
    int64_t              raw;
} promise_i64_v;

// int
typedef struct { } promise_int_t;
typedef struct { promise_int_t* _type; } promise_int_m;
typedef struct { promise_int_m* _variant; } promise_int_i;
typedef struct {
    void*                _vtable;
    promise_int_i*       _instance;
    int64_t              raw;
} promise_int_v;

// string
typedef struct { } promise_string_t;
typedef struct { promise_string_t* _type; } promise_string_m;
typedef struct {
    promise_string_m*    _variant;
    int64_t              len;
    char                 data[];
} promise_string_i;
typedef struct {
    void*                _vtable;
    promise_string_i*    _instance;
} promise_string_v;

// u8
typedef struct { } promise_u8_t;
typedef struct { promise_u8_t* _type; } promise_u8_m;
typedef struct { promise_u8_m* _variant; } promise_u8_i;
typedef struct {
    void*                _vtable;
    promise_u8_i*        _instance;
    uint8_t              raw;
} promise_u8_v;

// u16
typedef struct { } promise_u16_t;
typedef struct { promise_u16_t* _type; } promise_u16_m;
typedef struct { promise_u16_m* _variant; } promise_u16_i;
typedef struct {
    void*                _vtable;
    promise_u16_i*       _instance;
    uint16_t             raw;
} promise_u16_v;

// u32
typedef struct { } promise_u32_t;
typedef struct { promise_u32_t* _type; } promise_u32_m;
typedef struct { promise_u32_m* _variant; } promise_u32_i;
typedef struct {
    void*                _vtable;
    promise_u32_i*       _instance;
    uint32_t             raw;
} promise_u32_v;

// u64
typedef struct { } promise_u64_t;
typedef struct { promise_u64_t* _type; } promise_u64_m;
typedef struct { promise_u64_m* _variant; } promise_u64_i;
typedef struct {
    void*                _vtable;
    promise_u64_i*       _instance;
    uint64_t             raw;
} promise_u64_v;

// uint
typedef struct { } promise_uint_t;
typedef struct { promise_uint_t* _type; } promise_uint_m;
typedef struct { promise_uint_m* _variant; } promise_uint_i;
typedef struct {
    void*                _vtable;
    promise_uint_i*      _instance;
    uint64_t             raw;
} promise_uint_v;

#endif // PROMISE_BINDINGS_H
