package bindgen

import (
	"fmt"
	"strings"
	"unicode"
	"unicode/utf8"
)

// GenerateJSGlue generates the companion JavaScript file that implements the
// promise_env WASM imports for browser-targeted WebIDL bindings.
//
// The generated JS provides:
// - Reference table (refStore/refLoad/refRelease) for JS object handles
// - String marshalling (readString/writeString) via TextEncoder/TextDecoder
// - Per-import function implementations dispatching to actual DOM/browser APIs
// - WASM instantiation boilerplate
func GenerateJSGlue(modules []*Module) string {
	g := &jsGlueGenerator{}
	return g.generate(modules)
}

type jsGlueGenerator struct {
	buf strings.Builder
}

func (g *jsGlueGenerator) generate(modules []*Module) string {
	g.emitHeader()
	g.emitRefTable()
	g.emitStringHelpers()
	g.emitExitSignal()
	g.emitLineBufferHelpers()
	g.emitImportObject(modules)
	g.emitInstantiation()
	return g.buf.String()
}

func (g *jsGlueGenerator) writef(format string, args ...interface{}) {
	fmt.Fprintf(&g.buf, format, args...)
}

func (g *jsGlueGenerator) write(s string) {
	g.buf.WriteString(s)
}

func (g *jsGlueGenerator) emitHeader() {
	g.write(`// Auto-generated by promise bind webidl — do not edit.
// This file provides the JS glue for WASM browser bindings.

"use strict";

let wasm;

`)
}

func (g *jsGlueGenerator) emitRefTable() {
	g.write(`// --- Reference Table ---
// Maps integer handles to JS objects. Handle 0 is reserved (null).
const _refs = [undefined]; // slot 0 = null sentinel
const _freeList = [];

function _refStore(obj) {
  if (_freeList.length > 0) {
    const idx = _freeList.pop();
    _refs[idx] = obj;
    return idx;
  }
  _refs.push(obj);
  return _refs.length - 1;
}

function _refLoad(handle) {
  return _refs[handle];
}

function _refRelease(handle) {
  if (handle <= 0) return;
  _refs[handle] = undefined;
  _freeList.push(handle);
}

`)
}

func (g *jsGlueGenerator) emitStringHelpers() {
	g.write(`// --- String Marshalling ---
const _encoder = new TextEncoder();
const _decoder = new TextDecoder("utf-8");

function _readString(ptr, len) {
  const mem = new Uint8Array(wasm.exports.memory.buffer);
  return _decoder.decode(mem.subarray(ptr, ptr + len));
}

function _writeString(str) {
  const bytes = _encoder.encode(str);
  const ptr = wasm.exports.cabi_realloc(0, 0, 1, bytes.length);
  const mem = new Uint8Array(wasm.exports.memory.buffer);
  mem.set(bytes, ptr);
  return { ptr, len: bytes.length };
}

`)
}

// emitExitSignal defines the typed sentinel exit() throws to unwind the
// synchronous WASM call stack — the only way to abort a WASM function from a
// JS import. Carrying the real exit code lets init() tell a normal main()
// return (pal_exit(0)) apart from a panic or an explicit non-zero exit(),
// instead of matching on a bare Error's .message string, which would also
// swallow any unrelated JS error that happened to carry the same text.
func (g *jsGlueGenerator) emitExitSignal() {
	g.write(`class _ExitSignal extends Error {
  constructor(code) {
    super("promise_env.exit");
    this.code = code;
  }
}

`)
}

// emitLineBufferHelpers defines the per-fd line buffering that
// promise_env.write uses. console.log/console.error each add their own
// trailing newline, but Promise's print_line already appends
// Platform.line_separator before the write ever reaches the PAL (see
// definePrintStringBody in internal/codegen/io.go) — logging each write
// verbatim would double every line, and a write with no trailing newline
// would become its own console line, making it impossible to build one line
// out of several print() calls. Buffering per fd and flushing only on
// complete lines fixes both.
func (g *jsGlueGenerator) emitLineBufferHelpers() {
	g.write(`const _lineBuf = { 1: "", 2: "" };

function _flushLine(fd, line) {
  (fd === 2 ? console.error : console.log)(line);
}

function _writeChunk(fd, text) {
  const pending = _lineBuf[fd] + text;
  const lines = pending.split("\n");
  _lineBuf[fd] = lines.pop();
  for (const line of lines) _flushLine(fd, line);
}

function _flushRemainder() {
  for (const fd of [1, 2]) {
    if (_lineBuf[fd]) {
      _flushLine(fd, _lineBuf[fd]);
      _lineBuf[fd] = "";
    }
  }
}

`)
}

// emitBasePromiseEnvImports writes the promise_env.write/exit/monotonic_nanos
// entries every Promise wasm32-web binary imports unconditionally, regardless
// of which WebIDL bindings it also uses. Without these, WebAssembly.instantiate
// throws a LinkError before any binding code — or _initialize — ever runs, so
// the exit-unwind catch in emitInstantiation has nothing to catch (T1506).
func (g *jsGlueGenerator) emitBasePromiseEnvImports() {
	g.write(`    write(fd, ptr, len) {
      // i64 args/returns are BigInts in default WebAssembly mode.
      const lenN = Number(len);
      if (lenN > 0) {
        const mem = new Uint8Array(wasm.exports.memory.buffer, Number(ptr), lenN);
        _writeChunk(Number(fd) === 2 ? 2 : 1, _decoder.decode(mem));
      }
      return BigInt(lenN);
    },
    exit(code) {
      throw new _ExitSignal(Number(code));
    },
    monotonic_nanos() {
      return BigInt(Math.round(performance.now() * 1e6));
    },
`)
}

func (g *jsGlueGenerator) emitImportObject(modules []*Module) {
	g.write("// --- Import Implementations ---\n")
	g.write("const importObject = {\n")

	for _, m := range modules {
		g.writef("  %s: {\n", m.ImportModule)

		if m.ImportModule == "promise_env" {
			g.emitBasePromiseEnvImports()
		}

		// Resource drop functions
		for _, res := range m.Resources {
			if res.Drop {
				importName := res.Name + ".drop"
				g.writef("    \"%s\"(handle) {\n", importName)
				g.write("      _refRelease(handle);\n")
				g.write("    },\n")
			}

			for _, method := range res.Methods {
				g.emitMethodImport(res.Name, method)
			}
		}

		// Free functions
		for _, f := range m.Functions {
			g.emitFreeFuncImport(f)
		}

		g.write("  },\n")
	}

	g.write("};\n\n")
}

func (g *jsGlueGenerator) emitMethodImport(resourceName string, f Func) {
	importName := f.ImportName
	if importName == "" {
		importName = resourceName + "." + f.Name
	}

	// Build JS parameter list
	jsParams := g.buildJSParams(f)

	g.writef("    \"%s\"(%s) {\n", importName, strings.Join(jsParams, ", "))

	switch f.Kind {
	case FuncConstructor:
		g.emitConstructorBody(resourceName, f, jsParams)
	case FuncStatic:
		g.emitStaticBody(resourceName, f, jsParams)
	default:
		g.emitMethodBody(resourceName, f, jsParams)
	}

	g.write("    },\n")
}

func (g *jsGlueGenerator) emitFreeFuncImport(f Func) {
	importName := f.ImportName
	if importName == "" {
		importName = f.Name
	}
	jsParams := g.buildJSParams(f)

	g.writef("    \"%s\"(%s) {\n", importName, strings.Join(jsParams, ", "))
	// Free functions just call the global function
	g.writef("      return %s(%s);\n", idlCamelCase(f.Name), strings.Join(jsParams, ", "))
	g.write("    },\n")
}

func (g *jsGlueGenerator) buildJSParams(f Func) []string {
	var params []string

	// Methods get a handle parameter first
	if f.Kind == FuncMethod {
		params = append(params, "handle")
	}

	for _, p := range f.Params {
		name := jsParamName(p.Name)
		ref := p.Type
		// Unwrap option for the flat parameter
		if ref.Kind == OptionKind {
			ref = *ref.Elem
		}
		// String parameters are ptr+len pairs
		if isStringType(ref) {
			params = append(params, name+"_ptr", name+"_len")
		} else {
			params = append(params, name)
		}
	}

	return params
}

func (g *jsGlueGenerator) emitConstructorBody(resourceName string, f Func, jsParams []string) {
	// Convert parameters, call new Constructor(...), store ref
	args := g.buildJSCallArgs(f)
	g.writef("      const obj = new %s(%s);\n", resourceName, strings.Join(args, ", "))
	g.write("      return _refStore(obj);\n")
}

func (g *jsGlueGenerator) emitStaticBody(resourceName string, f Func, jsParams []string) {
	args := g.buildJSCallArgs(f)
	jsName := idlCamelCase(f.Name)
	call := fmt.Sprintf("%s.%s(%s)", resourceName, jsName, strings.Join(args, ", "))
	g.emitReturnConversion(f, call)
}

func (g *jsGlueGenerator) emitMethodBody(resourceName string, f Func, jsParams []string) {
	args := g.buildJSCallArgs(f)
	jsName := idlCamelCase(f.Name)

	// Check if this is an attribute getter/setter.
	// Attribute import names have 3 parts: "Type.attrName.get/set"
	// Operation import names have 2 parts: "Type.methodName"
	parts := strings.Split(f.ImportName, ".")
	if len(parts) == 3 && parts[2] == "get" {
		attrName := idlCamelCase(parts[1])
		call := fmt.Sprintf("_refLoad(handle).%s", attrName)
		g.emitReturnConversion(f, call)
		return
	}
	if len(parts) == 3 && parts[2] == "set" {
		attrName := idlCamelCase(parts[1])
		g.writef("      _refLoad(handle).%s = %s;\n", attrName, strings.Join(args, ", "))
		return
	}

	call := fmt.Sprintf("_refLoad(handle).%s(%s)", jsName, strings.Join(args, ", "))
	g.emitReturnConversion(f, call)
}

func (g *jsGlueGenerator) buildJSCallArgs(f Func) []string {
	var args []string
	for _, p := range f.Params {
		name := jsParamName(p.Name)
		ref := p.Type
		if ref.Kind == OptionKind {
			ref = *ref.Elem
		}
		if isStringType(ref) {
			args = append(args, fmt.Sprintf("_readString(%s_ptr, %s_len)", name, name))
		} else if isRefType(ref) {
			args = append(args, fmt.Sprintf("_refLoad(%s)", name))
		} else {
			args = append(args, name)
		}
	}
	return args
}

func (g *jsGlueGenerator) emitReturnConversion(f Func, call string) {
	if len(f.Results) == 0 {
		g.writef("      %s;\n", call)
		return
	}
	isNullable := f.Results[0].Kind == OptionKind
	ret := f.Results[0]
	// Unwrap option for the flat return type
	if ret.Kind == OptionKind && ret.Elem != nil {
		ret = *ret.Elem
	}
	if isStringType(ret) {
		// String return: write to linear memory, return ptr+len via retarea
		g.writef("      const result = %s;\n", call)
		if isNullable {
			g.write("      if (result == null) return 0;\n")
		}
		g.write("      const { ptr, len } = _writeString(String(result));\n")
		g.write("      const retarea = wasm.exports.cabi_retarea();\n")
		g.write("      const view = new DataView(wasm.exports.memory.buffer);\n")
		g.write("      view.setInt32(retarea, ptr, true);\n")
		g.write("      view.setInt32(retarea + 4, len, true);\n")
		g.write("      return retarea;\n")
	} else if isRefType(ret) {
		if isNullable {
			g.writef("      const result = %s;\n", call)
			g.write("      if (result == null) return 0;\n")
			g.write("      return _refStore(result);\n")
		} else {
			g.writef("      return _refStore(%s);\n", call)
		}
	} else {
		g.writef("      return %s;\n", call)
	}
}

func (g *jsGlueGenerator) emitInstantiation() {
	g.write(`// --- WASM Instantiation ---
export async function init(wasmPath) {
  const response = await fetch(wasmPath);
  const { instance } = await WebAssembly.instantiateStreaming(response, importObject);
  wasm = instance;

  // Store global references
  _refStore(globalThis);           // handle 1 = globalThis
  if (typeof document !== "undefined") {
    _refStore(document);           // handle 2 = document
  }
  if (typeof console !== "undefined") {
    _refStore(console);            // handle 3 = console
  }

  // Call WASM _initialize if exported. A normal main() return is signaled by
  // pal_exit(0), which lowers to the promise_env.exit import — the only way
  // to abort a synchronous WASM call from a JS import is to throw, so exit()
  // always throws to unwind the call stack. That's expected on success, not
  // a crash, so swallow exactly that case; a non-zero code (a panic, or an
  // explicit exit()) must still propagate so the caller learns the run
  // failed instead of getting exports back silently (T1506).
  if (wasm.exports._initialize) {
    try {
      wasm.exports._initialize();
    } catch (e) {
      if (!(e instanceof _ExitSignal) || e.code !== 0) {
        _flushRemainder();
        throw e;
      }
    }
  }
  _flushRemainder();

  return wasm.exports;
}

export { _refStore, _refLoad, _refRelease };
`)
}

// isStringType checks if a TypeRef maps to a string in the binding IR.
func isStringType(ref TypeRef) bool {
	return ref.Kind == BuiltinKind && ref.Builtin == "string"
}

// isRefType checks if a TypeRef maps to a JS object reference (handle).
//
// This intentionally returns true for *every* NamedKind, including JsValue. On the
// JS side a JsValue genuinely IS a ref-table handle (a JS value is stored/loaded via
// _refStore/_refLoad, identical to a resource), so the existing read/write glue is
// correct for it here. The Promise (WASM) side is where JsValue diverges from a
// resource — it marshals to/from the JsValue *enum* rather than an `i32 _handle`
// field; that asymmetry is handled in codegen.go (isJsValueRef and friends, T0723).
// Do NOT exclude JsValue here, or the JS-side conversion will break.
func isRefType(ref TypeRef) bool {
	if ref.Kind == NamedKind {
		return true
	}
	return false
}

// jsParamName converts a snake_case parameter name to a JS-safe identifier.
func jsParamName(name string) string {
	// Avoid JS reserved words
	switch name {
	case "default", "class", "function", "var", "let", "const", "this", "new", "delete", "in", "typeof":
		return name + "_"
	}
	return name
}

// idlCamelCase converts snake_case back to camelCase for JS method names.
// "get_element_by_id" → "getElementById"
func idlCamelCase(s string) string {
	parts := strings.Split(s, "_")
	if len(parts) <= 1 {
		return s
	}
	var b strings.Builder
	b.WriteString(parts[0])
	for _, part := range parts[1:] {
		if len(part) == 0 {
			continue
		}
		r, size := utf8.DecodeRuneInString(part)
		b.WriteRune(unicode.ToUpper(r))
		b.WriteString(part[size:])
	}
	return b.String()
}
