package codegen

import (
	"fmt"
	"io"
	"sort"

	"djabi.dev/go/promise_lang/internal/types"
)

// GenerateHeader writes a C header file defining all struct types and extern
// function declarations needed for the C runtime to match the LLVM IR.
func GenerateHeader(w io.Writer, layouts map[*types.Named]*TypeDeclLayout, externs []*ExternFunc) error {
	p := func(format string, args ...interface{}) error {
		_, err := fmt.Fprintf(w, format, args...)
		return err
	}
	ln := func(s string) error {
		_, err := fmt.Fprintln(w, s)
		return err
	}

	if err := ln("// Generated by the Promise compiler — DO NOT EDIT"); err != nil {
		return err
	}
	if err := ln("#ifndef PROMISE_BINDINGS_H"); err != nil {
		return err
	}
	if err := ln("#define PROMISE_BINDINGS_H"); err != nil {
		return err
	}
	if err := ln(""); err != nil {
		return err
	}
	if err := ln("#include <stdint.h>"); err != nil {
		return err
	}
	if err := ln(""); err != nil {
		return err
	}

	// Sort layouts by name for deterministic output.
	sorted := sortedLayouts(layouts)

	if err := ln("// === Type Layouts ==="); err != nil {
		return err
	}
	if err := ln(""); err != nil {
		return err
	}

	for _, entry := range sorted {
		layout := entry.layout
		if err := p("// %s\n", layout.PromiseName); err != nil {
			return err
		}
		if err := emitStructTypedef(w, layout.Type); err != nil {
			return err
		}
		if err := emitStructTypedef(w, layout.Variant); err != nil {
			return err
		}
		if err := emitStructTypedef(w, layout.Instance); err != nil {
			return err
		}
		if err := emitStructTypedef(w, layout.Value); err != nil {
			return err
		}
		if err := ln(""); err != nil {
			return err
		}
	}

	if len(externs) > 0 {
		if err := ln("// === Extern Function Declarations ==="); err != nil {
			return err
		}
		if err := ln(""); err != nil {
			return err
		}
		for _, ext := range externs {
			if err := emitExternDecl(w, ext, layouts); err != nil {
				return err
			}
		}
		if err := ln(""); err != nil {
			return err
		}
	}

	return ln("#endif // PROMISE_BINDINGS_H")
}

// layoutEntry pairs a named type with its layout for sorting.
type layoutEntry struct {
	name   string
	layout *TypeDeclLayout
}

// sortedLayouts returns layouts sorted by PromiseName for deterministic output.
func sortedLayouts(layouts map[*types.Named]*TypeDeclLayout) []layoutEntry {
	var entries []layoutEntry
	for _, layout := range layouts {
		entries = append(entries, layoutEntry{name: layout.PromiseName, layout: layout})
	}
	sort.Slice(entries, func(i, j int) bool {
		return entries[i].name < entries[j].name
	})
	return entries
}

// emitStructTypedef writes a single typedef struct for one struct layout.
func emitStructTypedef(w io.Writer, sl *StructLayout) error {
	if sl == nil {
		return nil
	}

	if len(sl.Fields) == 0 {
		_, err := fmt.Fprintf(w, "typedef struct { } %s;\n", sl.CName)
		return err
	}

	if _, err := fmt.Fprintf(w, "typedef struct {\n"); err != nil {
		return err
	}
	for i, f := range sl.Fields {
		if sl.IsFlexible && i == len(sl.Fields)-1 {
			// C99 flexible array member
			if _, err := fmt.Fprintf(w, "    %-20s %s[];\n", sl.FlexElemCType, f.Name); err != nil {
				return err
			}
		} else {
			if _, err := fmt.Fprintf(w, "    %-20s %s;\n", f.CType, f.Name); err != nil {
				return err
			}
		}
	}
	_, err := fmt.Fprintf(w, "} %s;\n", sl.CName)
	return err
}

// emitExternDecl writes a C function declaration for an extern function.
func emitExternDecl(w io.Writer, ext *ExternFunc, layouts map[*types.Named]*TypeDeclLayout) error {
	retCType := "void"
	if ext.ResultType != nil {
		named := extractNamed(ext.ResultType)
		if named != nil {
			if layout, ok := layouts[named]; ok {
				retCType = layout.Value.CName
			}
		}
	}

	if _, err := fmt.Fprintf(w, "%s %s(", retCType, ext.CName); err != nil {
		return err
	}

	for i, pt := range ext.ParamTypes {
		if i > 0 {
			if _, err := fmt.Fprint(w, ", "); err != nil {
				return err
			}
		}
		named := extractNamed(pt)
		if named == nil {
			if _, err := fmt.Fprintf(w, "void* %s", ext.Sig.Params()[i].Name()); err != nil {
				return err
			}
			continue
		}
		layout, ok := layouts[named]
		if !ok {
			if _, err := fmt.Fprintf(w, "void* %s", ext.Sig.Params()[i].Name()); err != nil {
				return err
			}
			continue
		}

		if isRefType(pt) {
			if _, err := fmt.Fprintf(w, "%s* %s", layout.Value.CName, ext.Sig.Params()[i].Name()); err != nil {
				return err
			}
		} else {
			if _, err := fmt.Fprintf(w, "%s %s", layout.Value.CName, ext.Sig.Params()[i].Name()); err != nil {
				return err
			}
		}
	}

	if len(ext.ParamTypes) == 0 {
		if _, err := fmt.Fprint(w, "void"); err != nil {
			return err
		}
	}

	_, err := fmt.Fprintln(w, ");")
	return err
}
