package codegen

import (
	"fmt"
	"io"
	"sort"

	"github.com/promise-language/promise/compiler/internal/types"
)

// GenerateHeader writes a C header file defining all struct types and extern
// function declarations needed for the C runtime to match the LLVM IR.
func GenerateHeader(w io.Writer, layouts map[*types.Named]*TypeDeclLayout, enumLayouts map[*types.Enum]*TypeDeclLayout, externs []*ExternFunc) error {
	p := func(format string, args ...interface{}) error {
		_, err := fmt.Fprintf(w, format, args...)
		return err
	}
	ln := func(s string) error {
		_, err := fmt.Fprintln(w, s)
		return err
	}

	if err := ln("// Generated by the Promise compiler — DO NOT EDIT"); err != nil {
		return err
	}
	if err := ln("#ifndef PROMISE_BINDINGS_H"); err != nil {
		return err
	}
	if err := ln("#define PROMISE_BINDINGS_H"); err != nil {
		return err
	}
	if err := ln(""); err != nil {
		return err
	}
	if err := ln("#include <stdint.h>"); err != nil {
		return err
	}
	if err := ln(""); err != nil {
		return err
	}

	// Sort layouts by name for deterministic output.
	sorted := sortedLayouts(layouts)

	if err := ln("// === Type Layouts ==="); err != nil {
		return err
	}
	if err := ln(""); err != nil {
		return err
	}

	for _, entry := range sorted {
		layout := entry.layout
		if err := p("// %s\n", layout.PromiseName); err != nil {
			return err
		}
		if err := emitStructTypedef(w, layout.Type); err != nil {
			return err
		}
		if err := emitStructTypedef(w, layout.Variant); err != nil {
			return err
		}
		if err := emitStructTypedef(w, layout.Instance); err != nil {
			return err
		}
		if err := emitStructTypedef(w, layout.Value); err != nil {
			return err
		}
		if err := ln(""); err != nil {
			return err
		}
	}

	// Emit enum type layouts
	sortedEnums := sortedEnumLayouts(enumLayouts)
	for _, entry := range sortedEnums {
		layout := entry.layout
		if err := p("// %s (enum)\n", layout.PromiseName); err != nil {
			return err
		}
		if err := emitStructTypedef(w, layout.Type); err != nil {
			return err
		}
		if err := emitStructTypedef(w, layout.Variant); err != nil {
			return err
		}
		if err := emitStructTypedef(w, layout.Instance); err != nil {
			return err
		}
		if err := emitStructTypedef(w, layout.Value); err != nil {
			return err
		}
		if err := ln(""); err != nil {
			return err
		}
	}

	if len(externs) > 0 {
		if err := ln("// === Extern Function Declarations ==="); err != nil {
			return err
		}
		if err := ln(""); err != nil {
			return err
		}
		for _, ext := range externs {
			if err := emitExternDecl(w, ext, layouts, enumLayouts); err != nil {
				return err
			}
		}
		if err := ln(""); err != nil {
			return err
		}
	}

	return ln("#endif // PROMISE_BINDINGS_H")
}

// layoutEntry pairs a named type with its layout for sorting.
type layoutEntry struct {
	name   string
	layout *TypeDeclLayout
}

// sortedLayouts returns layouts sorted by PromiseName for deterministic output.
func sortedLayouts(layouts map[*types.Named]*TypeDeclLayout) []layoutEntry {
	var entries []layoutEntry
	for _, layout := range layouts {
		entries = append(entries, layoutEntry{name: layout.PromiseName, layout: layout})
	}
	sort.Slice(entries, func(i, j int) bool {
		return entries[i].name < entries[j].name
	})
	return entries
}

// sortedEnumLayouts returns enum layouts sorted by PromiseName for deterministic output.
func sortedEnumLayouts(layouts map[*types.Enum]*TypeDeclLayout) []layoutEntry {
	var entries []layoutEntry
	for _, layout := range layouts {
		entries = append(entries, layoutEntry{name: layout.PromiseName, layout: layout})
	}
	sort.Slice(entries, func(i, j int) bool {
		return entries[i].name < entries[j].name
	})
	return entries
}

// emitStructTypedef writes a single typedef struct for one struct layout.
func emitStructTypedef(w io.Writer, sl *StructLayout) error {
	if sl == nil {
		return nil
	}

	if len(sl.Fields) == 0 {
		_, err := fmt.Fprintf(w, "typedef struct { } %s;\n", sl.CName)
		return err
	}

	if _, err := fmt.Fprintf(w, "typedef struct {\n"); err != nil {
		return err
	}
	for i, f := range sl.Fields {
		if sl.IsFlexible && i == len(sl.Fields)-1 {
			// C99 flexible array member
			if _, err := fmt.Fprintf(w, "    %-20s %s[];\n", sl.FlexElemCType, f.Name); err != nil {
				return err
			}
		} else {
			if _, err := fmt.Fprintf(w, "    %-20s %s;\n", f.CType, f.Name); err != nil {
				return err
			}
		}
	}
	_, err := fmt.Fprintf(w, "} %s;\n", sl.CName)
	return err
}

// lookupLayoutForHeadergen resolves a TypeDeclLayout for a type across both named and enum maps.
func lookupLayoutForHeadergen(typ types.Type, layouts map[*types.Named]*TypeDeclLayout, enumLayouts map[*types.Enum]*TypeDeclLayout) *TypeDeclLayout {
	if named := extractNamed(typ); named != nil {
		return layouts[named]
	}
	if enum := extractEnum(typ); enum != nil {
		return enumLayouts[enum]
	}
	return nil
}

// emitExternDecl writes a C function declaration for an extern function.
// Matches the LLVM IR ABI: all value struct params are passed by pointer,
// and struct returns use sret pattern (void return, first param is result pointer).
func emitExternDecl(w io.Writer, ext *ExternFunc, layouts map[*types.Named]*TypeDeclLayout, enumLayouts map[*types.Enum]*TypeDeclLayout) error {
	// sret: struct returns become void with first param as result pointer
	if _, err := fmt.Fprintf(w, "void %s(", ext.CName); err != nil {
		return err
	}

	paramIdx := 0
	if ext.ResultType != nil {
		if layout := lookupLayoutForHeadergen(ext.ResultType, layouts, enumLayouts); layout != nil {
			if _, err := fmt.Fprintf(w, "%s *sret", layout.Value.CName); err != nil {
				return err
			}
			paramIdx++
		}
	}

	for i, pt := range ext.ParamTypes {
		if paramIdx > 0 {
			if _, err := fmt.Fprint(w, ", "); err != nil {
				return err
			}
		}
		layout := lookupLayoutForHeadergen(pt, layouts, enumLayouts)
		if layout == nil {
			if _, err := fmt.Fprintf(w, "void* %s", ext.Sig.Params()[i].Name()); err != nil {
				return err
			}
			paramIdx++
			continue
		}

		// All params passed by pointer to match C ABI on ARM64
		if _, err := fmt.Fprintf(w, "%s *%s", layout.Value.CName, ext.Sig.Params()[i].Name()); err != nil {
			return err
		}
		paramIdx++
	}

	if paramIdx == 0 {
		if _, err := fmt.Fprint(w, "void"); err != nil {
			return err
		}
	}

	_, err := fmt.Fprintln(w, ");")
	return err
}
