package clitest

import (
	"os"
	"path/filepath"
	"runtime"
	"strings"
	"testing"
	"time"
)

// binTime is when the synthetic bin/promise was "built"; every source starts an
// hour older, so each test only has to move the one file it is about.
var binTime = time.Date(2026, 9, 16, 14, 35, 16, 0, time.UTC)

// fakeRoot builds a checkout-shaped tree: one file per input freshnessError
// looks at, all older than the binary.
func fakeRoot(t *testing.T) (root, bin string) {
	t.Helper()
	root = t.TempDir()
	for _, rel := range []string{
		"compiler/go.mod",
		"compiler/internal/codegen/extern.go",
		"compiler/internal/codegen/extern_test.go",
		"compiler/cmd/promise/resources/std/string.pr",
		"compiler/internal/testutil/testdata/std/string.pr",
		"modules/std/string.pr",
		"examples/hello.pr",
		"tools/build/winlink/def/kernel32.def",
		"catalog.toml",
		"docs/language-guide.md",
	} {
		writeStamped(t, root, rel, binTime.Add(-time.Hour))
	}
	bin = filepath.Join(root, "bin", binaryName())
	writeStamped(t, root, "bin/"+binaryName(), binTime)
	return root, bin
}

func writeStamped(t *testing.T, root, rel string, mod time.Time) {
	t.Helper()
	path := filepath.Join(root, filepath.FromSlash(rel))
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(path, []byte("x\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := os.Chtimes(path, mod, mod); err != nil {
		t.Fatal(err)
	}
}

func TestFreshWhenNothingIsNewerThanTheBinary(t *testing.T) {
	root, bin := fakeRoot(t)
	if err := freshnessError(root, bin); err != nil {
		t.Fatalf("want fresh, got: %v", err)
	}
}

// The T2134 shape: a product source edited after the binary was built. Each of
// these inputs is one bin/build's own isBinaryUpToDate checks, so bin/build
// rebuilds for the same edit and the message's command clears the failure.
func TestStaleWhenASourceIsNewerThanTheBinary(t *testing.T) {
	for _, rel := range []string{
		"compiler/internal/codegen/extern.go",
		"modules/std/string.pr",
		"examples/hello.pr",
		"tools/build/winlink/def/kernel32.def",
		"catalog.toml",
		"docs/language-guide.md",
	} {
		t.Run(rel, func(t *testing.T) {
			root, bin := fakeRoot(t)
			writeStamped(t, root, rel, binTime.Add(time.Hour))

			err := freshnessError(root, bin)
			if err == nil {
				t.Fatalf("%s is newer than the binary, want stale", rel)
			}
			if !strings.Contains(err.Error(), rel) {
				t.Errorf("message does not name the offending file %s:\n%v", rel, err)
			}
		})
	}
}

// bin/build writes both of these trees itself on the way to producing the
// binary, and skips them for exactly that reason. Treating them as sources
// would report every freshly built tree as stale — a failure bin/build could
// never clear, which is the wedge this check must not create.
func TestGeneratedTreesAreNotSources(t *testing.T) {
	for _, rel := range []string{
		"compiler/cmd/promise/resources/std/string.pr",
		"compiler/internal/testutil/testdata/std/string.pr",
	} {
		t.Run(rel, func(t *testing.T) {
			root, bin := fakeRoot(t)
			writeStamped(t, root, rel, binTime.Add(time.Hour))

			if err := freshnessError(root, bin); err != nil {
				t.Fatalf("%s is generated by the build, want fresh, got: %v", rel, err)
			}
		})
	}
}

// go build never compiles a _test.go file into bin/promise, so editing one of
// these suites' own tests cannot make the artifact stale — and demanding a
// rebuild for it would put a rebuild in the middle of every edit-test loop.
func TestGoTestFilesAreNotSources(t *testing.T) {
	root, bin := fakeRoot(t)
	writeStamped(t, root, "compiler/internal/codegen/extern_test.go", binTime.Add(time.Hour))

	if err := freshnessError(root, bin); err != nil {
		t.Fatalf("want fresh, got: %v", err)
	}
}

// A tree that is missing one of the directories is walked, not failed — the
// same answer anySourceNewer gives for a directory that does not exist.
func TestMissingSourceDirectoryIsNotStale(t *testing.T) {
	root, bin := fakeRoot(t)
	if err := os.RemoveAll(filepath.Join(root, "examples")); err != nil {
		t.Fatal(err)
	}
	if err := freshnessError(root, bin); err != nil {
		t.Fatalf("want fresh, got: %v", err)
	}
}

func TestMessageNamesTheNewestSourceAndBothBuildSpellings(t *testing.T) {
	root, bin := fakeRoot(t)
	writeStamped(t, root, "compiler/internal/codegen/extern.go", binTime.Add(time.Hour))
	writeStamped(t, root, "modules/std/string.pr", binTime.Add(2*time.Hour))

	err := freshnessError(root, bin)
	if err == nil {
		t.Fatal("want stale")
	}
	msg := err.Error()

	if !strings.Contains(msg, "modules/std/string.pr") {
		t.Errorf("message names a file other than the newest source:\n%s", msg)
	}
	// Both spellings come from the helper that produced them, so this test is
	// about the message carrying them in the right order — not about what they
	// are on this platform. TestBuildCommandsSpellBothForms pins that, and
	// pinning it a second time here is what made this assertion POSIX-only:
	// the message says `bin\build` on Windows, so the hard-coded `bin/build`
	// could never be found and the test failed on every Windows run (T2152).
	wantAbs, wantRelative := buildCommands(root)
	absAt := strings.Index(msg, wantAbs)
	relAt := strings.Index(msg, wantRelative+" from the repo root")
	if absAt < 0 || relAt < 0 {
		t.Fatalf("message must name both spellings of the rebuild command:\n%s", msg)
	}
	// The absolute path resolves from any directory and so comes first; the
	// bare spelling only works at the repo root (docs/build-tools.md).
	if absAt > relAt {
		t.Errorf("absolute rebuild command must come before the relative one:\n%s", msg)
	}
}

// Every test in a package asks the same question; the walk answers it once.
func TestFreshnessIsAnsweredOncePerBinary(t *testing.T) {
	root, bin := fakeRoot(t)
	if err := cachedFreshnessError(root, bin); err != nil {
		t.Fatalf("want fresh, got: %v", err)
	}
	writeStamped(t, root, "compiler/internal/codegen/extern.go", binTime.Add(time.Hour))
	if err := cachedFreshnessError(root, bin); err != nil {
		t.Fatalf("cached answer must not be recomputed mid-run, got: %v", err)
	}
}

// A subtree the walk cannot read is skipped, not fatal: this check exists to
// tell a caller their binary is old, and it must never be the reason a suite
// cannot run at all.
func TestUnreadableDirectoryDoesNotFailTheWalk(t *testing.T) {
	if runtime.GOOS == "windows" || os.Geteuid() == 0 {
		t.Skip("permission bits do not deny directory reads here")
	}
	root, bin := fakeRoot(t)
	locked := filepath.Join(root, "compiler", "internal", "locked")
	if err := os.MkdirAll(locked, 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.Chmod(locked, 0o000); err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() { os.Chmod(locked, 0o755) })

	if err := freshnessError(root, bin); err != nil {
		t.Fatalf("want fresh, got: %v", err)
	}
}
